version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:

  api-install:
    executor:
      name: node/default
    working_directory: ~/eldercare/server
    steps:
      - checkout:
          path: ~/eldercare  
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: |
          npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/eldercare/server/node_modules
workflows:
  build-and-test:
    jobs:
      - api-install