version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  api-test:
    executor:
      name: node/default
    working_directory: ~/eldercare/server
    steps:
      - attach_workspace:
          at: ~/eldercare
      - run: 
          command: |
            cd ~/eldercare/server
            npm run test 
  api-install:
    executor:
      name: node/default
    working_directory: ~/eldercare/server
    steps:
      - checkout:
          path: ~/eldercare  
      - run: |
          npm i
workflows:
  build-and-test:
    jobs:
      - api-install
      - api-test:
          requires:
            - api-install