version: 2.1
executors:
  node:
    docker:
      - image: 'circleci/node:16'
    shell: /bin/bash
    resource_class: small
jobs: 
  test:
    executor:
      name: node
    working_directory: ~/eldercare/server
    steps:
      - checkout:
          path: ~/eldercare  
      - attach_workspace:
          at: ~/eldercare
      - run: npm run test
      - run: npm run build
  install:
    executor:
      name: node
    working_directory: ~/eldercare/server
    steps:
      - checkout:
          path: ~/eldercare  
      - run: npm install
      - persist_to_workspace:
          root: ~/eldercare
          paths:
            - .
workflows:
  build-and-test:
    jobs:
      - install
      - test:
          requires:
            - install