version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:

  build-and-test:
    executor:
      name: node/default
    working_directory: ~/eldercare/server
    steps:
      - checkout:
          path: ~/eldercare 
      - run: find "$PWD"
workflows:
  build-and-test:
    jobs:
      - build-and-test