version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs: 
  install-and-test:
    executor:
      name: node/default
    working_directory: ~/eldercare/server
    steps:
      - checkout:
          path: ~/eldercare  
      - run: npm istall
      - run: npm run start
workflows:
  build-and-test:
    jobs:
      - install-and-test