version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs: 
  test:
    executor:
      name: node/default
    working_directory: ~/eldercare/server
    steps:
      - checkout:
          path: ~/eldercare  
      - attach_workspace:
          at: ~/eldercare
      - run: npm run test
  install:
    executor:
      name: node/default
    working_directory: ~/eldercare/server
    steps:
      - checkout:
          path: ~/eldercare  
      - run: npm install
      - persist_to_workspace:
          root: ~/eldercare
          paths:
            - .
workflows:
  build-and-test:
    jobs:
      - install
      - test:
          requires:
            - install