version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    executor:
      name: node/default
    working_directory: ~/eldercare/server
    steps:
      - checkout:
          path: ~/eldercare 
      - node/install-packages:
          app-dir: ~/server
      - run:
          command: npm run test
workflows:
  build-and-test:
    jobs:
      - build-and-test
